# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuarkX_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSuper', models.BooleanField(default=False)),
                ('isReport', models.BooleanField(default=False)),
                ('isNormal', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
